/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class ExecutionModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ExecutionModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ExecutionModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public FilterChain createFilterChain() {
    long cPtr = opencvpJNI.ExecutionModel_createFilterChain(swigCPtr, this);
    return (cPtr == 0) ? null : new FilterChain(cPtr, true);
  }

  public FilterChain loadFilterChain(String path) {
    long cPtr = opencvpJNI.ExecutionModel_loadFilterChain(swigCPtr, this, path);
    return (cPtr == 0) ? null : new FilterChain(cPtr, true);
  }

  public void saveFilterChain(FilterChain filterChain, String path) {
    opencvpJNI.ExecutionModel_saveFilterChain(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain, path);
  }

  public int getFilterChainInputPortCount(FilterChain filterChain) {
    return opencvpJNI.ExecutionModel_getFilterChainInputPortCount(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain);
  }

  public int getFilterChainOutputPortCount(FilterChain filterChain) {
    return opencvpJNI.ExecutionModel_getFilterChainOutputPortCount(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain);
  }

  public PortType getFilterChainInputPortType(FilterChain filterChain, int portIndex) {
    return PortType.swigToEnum(opencvpJNI.ExecutionModel_getFilterChainInputPortType(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain, portIndex));
  }

  public PortType getFilterChainOutputPortType(FilterChain filterChain, int portIndex) {
    return PortType.swigToEnum(opencvpJNI.ExecutionModel_getFilterChainOutputPortType(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain, portIndex));
  }

  public void setFilterChainImageInputPortData(FilterChain filterChain, int portIndex, int width, int height, ImageDataType dataType, short[] data) {
    opencvpJNI.ExecutionModel_setFilterChainImageInputPortData(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain, portIndex, width, height, dataType.swigValue(), data);
  }

  public void executeFilterChain(FilterChain filterChain) {
    opencvpJNI.ExecutionModel_executeFilterChain(swigCPtr, this, FilterChain.getCPtr(filterChain), filterChain);
  }

  public FilterLibraryVector getLoadedFilterLibraries() {
    return new FilterLibraryVector(opencvpJNI.ExecutionModel_getLoadedFilterLibraries(swigCPtr, this), true);
  }

  public static ExecutionModel getInstance() {
    return new ExecutionModel(opencvpJNI.ExecutionModel_getInstance(), false);
  }

}
