/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class FilterChain extends InputPortContainer {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public FilterChain(long cPtr, boolean cMemoryOwn) {
    super(opencvpJNI.FilterChain_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FilterChain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        opencvpJNI.delete_FilterChain(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void addFilter(Filter filter) {
    opencvpJNI.FilterChain_addFilter(swigCPtr, this, Filter.getCPtr(filter), filter);
  }

  public void execute() {
    opencvpJNI.FilterChain_execute(swigCPtr, this);
  }

}
