/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class FilterLibrary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public FilterLibrary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FilterLibrary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opencvpJNI.delete_FilterLibrary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean isValid() {
    return opencvpJNI.FilterLibrary_isValid(swigCPtr, this);
  }

  public String getVendor() {
    return opencvpJNI.FilterLibrary_getVendor(swigCPtr, this);
  }

  public String getName() {
    return opencvpJNI.FilterLibrary_getName(swigCPtr, this);
  }

  public String getVersion() {
    return opencvpJNI.FilterLibrary_getVersion(swigCPtr, this);
  }

  public String getLibraryName() {
    return opencvpJNI.FilterLibrary_getLibraryName(swigCPtr, this);
  }

  public StringVector getFilterClassNames() {
    return new StringVector(opencvpJNI.FilterLibrary_getFilterClassNames(swigCPtr, this), true);
  }

}
