/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class ImageInputPort extends InputPort {
  private long swigCPtr;

  public ImageInputPort(long cPtr, boolean cMemoryOwn) {
    super(opencvpJNI.ImageInputPort_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImageInputPort obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opencvpJNI.delete_ImageInputPort(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

}
