/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class InputPortVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public InputPortVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(InputPortVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opencvpJNI.delete_InputPortVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InputPortVector() {
    this(opencvpJNI.new_InputPortVector__SWIG_0(), true);
  }

  public InputPortVector(long n) {
    this(opencvpJNI.new_InputPortVector__SWIG_1(n), true);
  }

  public long size() {
    return opencvpJNI.InputPortVector_size(swigCPtr, this);
  }

  public long capacity() {
    return opencvpJNI.InputPortVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    opencvpJNI.InputPortVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return opencvpJNI.InputPortVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    opencvpJNI.InputPortVector_clear(swigCPtr, this);
  }

  public void add(InputPort x) {
    opencvpJNI.InputPortVector_add(swigCPtr, this, InputPort.getCPtr(x), x);
  }

  public InputPort get(int i) {
    long cPtr = opencvpJNI.InputPortVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new InputPort(cPtr, false);
  }

  public void set(int i, InputPort val) {
    opencvpJNI.InputPortVector_set(swigCPtr, this, i, InputPort.getCPtr(val), val);
  }

}
