/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class OutputPortVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public OutputPortVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OutputPortVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opencvpJNI.delete_OutputPortVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OutputPortVector() {
    this(opencvpJNI.new_OutputPortVector__SWIG_0(), true);
  }

  public OutputPortVector(long n) {
    this(opencvpJNI.new_OutputPortVector__SWIG_1(n), true);
  }

  public long size() {
    return opencvpJNI.OutputPortVector_size(swigCPtr, this);
  }

  public long capacity() {
    return opencvpJNI.OutputPortVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    opencvpJNI.OutputPortVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return opencvpJNI.OutputPortVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    opencvpJNI.OutputPortVector_clear(swigCPtr, this);
  }

  public void add(OutputPort x) {
    opencvpJNI.OutputPortVector_add(swigCPtr, this, OutputPort.getCPtr(x), x);
  }

  public OutputPort get(int i) {
    long cPtr = opencvpJNI.OutputPortVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new OutputPort(cPtr, false);
  }

  public void set(int i, OutputPort val) {
    opencvpJNI.OutputPortVector_set(swigCPtr, this, i, OutputPort.getCPtr(val), val);
  }

}
