/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public final class PortType {
  public final static PortType PORT_TYPE_IMAGE = new PortType("PORT_TYPE_IMAGE");
  public final static PortType PORT_TYPE_COUNT = new PortType("PORT_TYPE_COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PortType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PortType.class + " with value " + swigValue);
  }

  private PortType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PortType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PortType(String swigName, PortType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PortType[] swigValues = { PORT_TYPE_IMAGE, PORT_TYPE_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

