/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package im.jeanfrancois.opencvp.nativeinterface.internal;

public class PropertyVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PropertyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opencvpJNI.delete_PropertyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PropertyVector() {
    this(opencvpJNI.new_PropertyVector__SWIG_0(), true);
  }

  public PropertyVector(long n) {
    this(opencvpJNI.new_PropertyVector__SWIG_1(n), true);
  }

  public long size() {
    return opencvpJNI.PropertyVector_size(swigCPtr, this);
  }

  public long capacity() {
    return opencvpJNI.PropertyVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    opencvpJNI.PropertyVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return opencvpJNI.PropertyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    opencvpJNI.PropertyVector_clear(swigCPtr, this);
  }

  public void add(Property x) {
    opencvpJNI.PropertyVector_add(swigCPtr, this, Property.getCPtr(x), x);
  }

  public Property get(int i) {
    long cPtr = opencvpJNI.PropertyVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Property(cPtr, false);
  }

  public void set(int i, Property val) {
    opencvpJNI.PropertyVector_set(swigCPtr, this, i, Property.getCPtr(val), val);
  }

}
