/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <string>


#include <stdexcept>


#include <vector>
#include <stdexcept>


#if defined(SWIG_NOINCLUDE) || defined(SWIG_NOARRAYS)


int SWIG_JavaArrayInBool (JNIEnv *jenv, jboolean **jarr, bool **carr, jbooleanArray input);
void SWIG_JavaArrayArgoutBool (JNIEnv *jenv, jboolean *jarr, bool *carr, jbooleanArray input);
jbooleanArray SWIG_JavaArrayOutBool (JNIEnv *jenv, bool *result, jsize sz);


int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input);
void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input);
jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz);


int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input);
void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input);
jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz);


int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input);
void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input);
jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz);


int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input);
void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input);
jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz);


int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input);
void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input);
jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz);


int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input);
void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz);


int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input);
void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input);
jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz);


int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input);
void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz);


int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input);
void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input);
jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz);


int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input);
void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input);
jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz);


int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input);
void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input);
jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz);


#else


/* bool[] support */
int SWIG_JavaArrayInBool (JNIEnv *jenv, jboolean **jarr, bool **carr, jbooleanArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetBooleanArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new bool[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = ((*jarr)[i] != 0);
  return 1;
}

void SWIG_JavaArrayArgoutBool (JNIEnv *jenv, jboolean *jarr, bool *carr, jbooleanArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jboolean)carr[i];
  jenv->ReleaseBooleanArrayElements(input, jarr, 0);
}

jbooleanArray SWIG_JavaArrayOutBool (JNIEnv *jenv, bool *result, jsize sz) {
  jboolean *arr;
  int i;
  jbooleanArray jresult = jenv->NewBooleanArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetBooleanArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jboolean)result[i];
  jenv->ReleaseBooleanArrayElements(jresult, arr, 0);
  return jresult;
}


/* signed char[] support */
int SWIG_JavaArrayInSchar (JNIEnv *jenv, jbyte **jarr, signed char **carr, jbyteArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetByteArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new signed char[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (signed char)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutSchar (JNIEnv *jenv, jbyte *jarr, signed char *carr, jbyteArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jbyte)carr[i];
  jenv->ReleaseByteArrayElements(input, jarr, 0);
}

jbyteArray SWIG_JavaArrayOutSchar (JNIEnv *jenv, signed char *result, jsize sz) {
  jbyte *arr;
  int i;
  jbyteArray jresult = jenv->NewByteArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetByteArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jbyte)result[i];
  jenv->ReleaseByteArrayElements(jresult, arr, 0);
  return jresult;
}


/* unsigned char[] support */
int SWIG_JavaArrayInUchar (JNIEnv *jenv, jshort **jarr, unsigned char **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetShortArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new unsigned char[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned char)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUchar (JNIEnv *jenv, jshort *jarr, unsigned char *carr, jshortArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  jenv->ReleaseShortArrayElements(input, jarr, 0);
}

jshortArray SWIG_JavaArrayOutUchar (JNIEnv *jenv, unsigned char *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = jenv->NewShortArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetShortArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  jenv->ReleaseShortArrayElements(jresult, arr, 0);
  return jresult;
}


/* short[] support */
int SWIG_JavaArrayInShort (JNIEnv *jenv, jshort **jarr, short **carr, jshortArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetShortArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new short[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (short)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutShort (JNIEnv *jenv, jshort *jarr, short *carr, jshortArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jshort)carr[i];
  jenv->ReleaseShortArrayElements(input, jarr, 0);
}

jshortArray SWIG_JavaArrayOutShort (JNIEnv *jenv, short *result, jsize sz) {
  jshort *arr;
  int i;
  jshortArray jresult = jenv->NewShortArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetShortArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jshort)result[i];
  jenv->ReleaseShortArrayElements(jresult, arr, 0);
  return jresult;
}


/* unsigned short[] support */
int SWIG_JavaArrayInUshort (JNIEnv *jenv, jint **jarr, unsigned short **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetIntArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new unsigned short[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned short)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUshort (JNIEnv *jenv, jint *jarr, unsigned short *carr, jintArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  jenv->ReleaseIntArrayElements(input, jarr, 0);
}

jintArray SWIG_JavaArrayOutUshort (JNIEnv *jenv, unsigned short *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = jenv->NewIntArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetIntArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  jenv->ReleaseIntArrayElements(jresult, arr, 0);
  return jresult;
}


/* int[] support */
int SWIG_JavaArrayInInt (JNIEnv *jenv, jint **jarr, int **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetIntArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new int[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (int)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutInt (JNIEnv *jenv, jint *jarr, int *carr, jintArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  jenv->ReleaseIntArrayElements(input, jarr, 0);
}

jintArray SWIG_JavaArrayOutInt (JNIEnv *jenv, int *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = jenv->NewIntArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetIntArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  jenv->ReleaseIntArrayElements(jresult, arr, 0);
  return jresult;
}


/* unsigned int[] support */
int SWIG_JavaArrayInUint (JNIEnv *jenv, jlong **jarr, unsigned int **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetLongArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new unsigned int[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned int)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUint (JNIEnv *jenv, jlong *jarr, unsigned int *carr, jlongArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  jenv->ReleaseLongArrayElements(input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutUint (JNIEnv *jenv, unsigned int *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = jenv->NewLongArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetLongArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  jenv->ReleaseLongArrayElements(jresult, arr, 0);
  return jresult;
}


/* long[] support */
int SWIG_JavaArrayInLong (JNIEnv *jenv, jint **jarr, long **carr, jintArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetIntArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new long[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (long)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutLong (JNIEnv *jenv, jint *jarr, long *carr, jintArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jint)carr[i];
  jenv->ReleaseIntArrayElements(input, jarr, 0);
}

jintArray SWIG_JavaArrayOutLong (JNIEnv *jenv, long *result, jsize sz) {
  jint *arr;
  int i;
  jintArray jresult = jenv->NewIntArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetIntArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jint)result[i];
  jenv->ReleaseIntArrayElements(jresult, arr, 0);
  return jresult;
}


/* unsigned long[] support */
int SWIG_JavaArrayInUlong (JNIEnv *jenv, jlong **jarr, unsigned long **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetLongArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new unsigned long[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (unsigned long)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutUlong (JNIEnv *jenv, jlong *jarr, unsigned long *carr, jlongArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  jenv->ReleaseLongArrayElements(input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutUlong (JNIEnv *jenv, unsigned long *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = jenv->NewLongArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetLongArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  jenv->ReleaseLongArrayElements(jresult, arr, 0);
  return jresult;
}


/* jlong[] support */
int SWIG_JavaArrayInLonglong (JNIEnv *jenv, jlong **jarr, jlong **carr, jlongArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetLongArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new jlong[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (jlong)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutLonglong (JNIEnv *jenv, jlong *jarr, jlong *carr, jlongArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jlong)carr[i];
  jenv->ReleaseLongArrayElements(input, jarr, 0);
}

jlongArray SWIG_JavaArrayOutLonglong (JNIEnv *jenv, jlong *result, jsize sz) {
  jlong *arr;
  int i;
  jlongArray jresult = jenv->NewLongArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetLongArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jlong)result[i];
  jenv->ReleaseLongArrayElements(jresult, arr, 0);
  return jresult;
}


/* float[] support */
int SWIG_JavaArrayInFloat (JNIEnv *jenv, jfloat **jarr, float **carr, jfloatArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetFloatArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new float[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (float)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutFloat (JNIEnv *jenv, jfloat *jarr, float *carr, jfloatArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jfloat)carr[i];
  jenv->ReleaseFloatArrayElements(input, jarr, 0);
}

jfloatArray SWIG_JavaArrayOutFloat (JNIEnv *jenv, float *result, jsize sz) {
  jfloat *arr;
  int i;
  jfloatArray jresult = jenv->NewFloatArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetFloatArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jfloat)result[i];
  jenv->ReleaseFloatArrayElements(jresult, arr, 0);
  return jresult;
}


/* double[] support */
int SWIG_JavaArrayInDouble (JNIEnv *jenv, jdouble **jarr, double **carr, jdoubleArray input) {
  int i;
  jsize sz;
  if (!input) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null array");
    return 0;
  }
  sz = jenv->GetArrayLength(input);
  *jarr = jenv->GetDoubleArrayElements(input, 0);
  if (!*jarr)
    return 0; 
  *carr = new double[sz]; 
  if (!*carr) {
    SWIG_JavaThrowException(jenv, SWIG_JavaOutOfMemoryError, "array memory allocation failed");
    return 0;
  }
  for (i=0; i<sz; i++)
    (*carr)[i] = (double)(*jarr)[i];
  return 1;
}

void SWIG_JavaArrayArgoutDouble (JNIEnv *jenv, jdouble *jarr, double *carr, jdoubleArray input) {
  int i;
  jsize sz = jenv->GetArrayLength(input);
  for (i=0; i<sz; i++)
    jarr[i] = (jdouble)carr[i];
  jenv->ReleaseDoubleArrayElements(input, jarr, 0);
}

jdoubleArray SWIG_JavaArrayOutDouble (JNIEnv *jenv, double *result, jsize sz) {
  jdouble *arr;
  int i;
  jdoubleArray jresult = jenv->NewDoubleArray(sz);
  if (!jresult)
    return NULL;
  arr = jenv->GetDoubleArrayElements(jresult, 0);
  if (!arr)
    return NULL;
  for (i=0; i<sz; i++)
    arr[i] = (jdouble)result[i];
  jenv->ReleaseDoubleArrayElements(jresult, arr, 0);
  return jresult;
}


#endif


#include "InputPort.h"
#include "OutputPort.h"
#include "Property.h"
#include "Container.h"
#include "ExecutionModel.h"
#include "FilterLibrary.h"
#include "FilterChain.h"
#include "Filter.h"

SWIGINTERN std::vector< std::string >::const_reference std_vector_Sl_std_string_Sg__get(std::vector< std::string > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_string_Sg__set(std::vector< std::string > *self,int i,std::vector< std::string >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< FilterLibrary * >::const_reference std_vector_Sl_FilterLibrary_Sm__Sg__get(std::vector< FilterLibrary * > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_FilterLibrary_Sm__Sg__set(std::vector< FilterLibrary * > *self,int i,std::vector< FilterLibrary * >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< InputPort * >::const_reference std_vector_Sl_InputPort_Sm__Sg__get(std::vector< InputPort * > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_InputPort_Sm__Sg__set(std::vector< InputPort * > *self,int i,std::vector< InputPort * >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< OutputPort * >::const_reference std_vector_Sl_OutputPort_Sm__Sg__get(std::vector< OutputPort * > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_OutputPort_Sm__Sg__set(std::vector< OutputPort * > *self,int i,std::vector< OutputPort * >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< Property * >::const_reference std_vector_Sl_Property_Sm__Sg__get(std::vector< Property * > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_Property_Sm__Sg__set(std::vector< Property * > *self,int i,std::vector< Property * >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1StringVector_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< std::string > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< std::string > *)new std::vector< std::string >();
  *(std::vector< std::string > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1StringVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< std::string >::size_type arg1 ;
  std::vector< std::string > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< std::string >::size_type)jarg1; 
  result = (std::vector< std::string > *)new std::vector< std::string >(arg1);
  *(std::vector< std::string > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  result = ((std::vector< std::string > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  result = ((std::vector< std::string > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  arg2 = (std::vector< std::string >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  result = (bool)((std::vector< std::string > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  std::vector< std::string >::value_type *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->push_back((std::vector< std::string >::value_type const &)*arg2);
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jstring jresult = 0 ;
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< std::string >::value_type *) &std_vector_Sl_std_string_Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_StringVector_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *arg3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  arg2 = (int)jarg2; 
  if(!jarg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return ;
  }
  const char *arg3_pstr = (const char *)jenv->GetStringUTFChars(jarg3, 0); 
  if (!arg3_pstr) return ;
  std::string arg3_str(arg3_pstr);
  arg3 = &arg3_str;
  jenv->ReleaseStringUTFChars(jarg3, arg3_pstr); 
  try {
    std_vector_Sl_std_string_Sg__set(arg1,arg2,(std::string const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1StringVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< std::string > *arg1 = (std::vector< std::string > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< std::string > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1FilterLibraryVector_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< FilterLibrary * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< FilterLibrary * > *)new std::vector< FilterLibrary * >();
  *(std::vector< FilterLibrary * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1FilterLibraryVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< FilterLibrary * >::size_type arg1 ;
  std::vector< FilterLibrary * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< FilterLibrary * >::size_type)jarg1; 
  result = (std::vector< FilterLibrary * > *)new std::vector< FilterLibrary * >(arg1);
  *(std::vector< FilterLibrary * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  std::vector< FilterLibrary * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  result = ((std::vector< FilterLibrary * > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  std::vector< FilterLibrary * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  result = ((std::vector< FilterLibrary * > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  std::vector< FilterLibrary * >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  arg2 = (std::vector< FilterLibrary * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  result = (bool)((std::vector< FilterLibrary * > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  std::vector< FilterLibrary * >::value_type *arg2 = 0 ;
  std::vector< FilterLibrary * >::value_type temp2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  temp2 = *(std::vector< FilterLibrary * >::value_type *)&jarg2;
  arg2 = (std::vector< FilterLibrary * >::value_type *)&temp2; 
  (arg1)->push_back((std::vector< FilterLibrary * >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  int arg2 ;
  std::vector< FilterLibrary * >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< FilterLibrary * >::value_type *) &std_vector_Sl_FilterLibrary_Sm__Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< FilterLibrary * >::value_type *)&jresult = *result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibraryVector_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  int arg2 ;
  std::vector< FilterLibrary * >::value_type *arg3 = 0 ;
  std::vector< FilterLibrary * >::value_type temp3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  arg2 = (int)jarg2; 
  temp3 = *(std::vector< FilterLibrary * >::value_type *)&jarg3;
  arg3 = (std::vector< FilterLibrary * >::value_type *)&temp3; 
  try {
    std_vector_Sl_FilterLibrary_Sm__Sg__set(arg1,arg2,(FilterLibrary *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1FilterLibraryVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< FilterLibrary * > *arg1 = (std::vector< FilterLibrary * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< FilterLibrary * > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1InputPortVector_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< InputPort * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< InputPort * > *)new std::vector< InputPort * >();
  *(std::vector< InputPort * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1InputPortVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< InputPort * >::size_type arg1 ;
  std::vector< InputPort * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< InputPort * >::size_type)jarg1; 
  result = (std::vector< InputPort * > *)new std::vector< InputPort * >(arg1);
  *(std::vector< InputPort * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  std::vector< InputPort * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  result = ((std::vector< InputPort * > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  std::vector< InputPort * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  result = ((std::vector< InputPort * > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  std::vector< InputPort * >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  arg2 = (std::vector< InputPort * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  result = (bool)((std::vector< InputPort * > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  std::vector< InputPort * >::value_type *arg2 = 0 ;
  std::vector< InputPort * >::value_type temp2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  temp2 = *(std::vector< InputPort * >::value_type *)&jarg2;
  arg2 = (std::vector< InputPort * >::value_type *)&temp2; 
  (arg1)->push_back((std::vector< InputPort * >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  int arg2 ;
  std::vector< InputPort * >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< InputPort * >::value_type *) &std_vector_Sl_InputPort_Sm__Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< InputPort * >::value_type *)&jresult = *result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPortVector_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  int arg2 ;
  std::vector< InputPort * >::value_type *arg3 = 0 ;
  std::vector< InputPort * >::value_type temp3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  arg2 = (int)jarg2; 
  temp3 = *(std::vector< InputPort * >::value_type *)&jarg3;
  arg3 = (std::vector< InputPort * >::value_type *)&temp3; 
  try {
    std_vector_Sl_InputPort_Sm__Sg__set(arg1,arg2,(InputPort *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1InputPortVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< InputPort * > *arg1 = (std::vector< InputPort * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< InputPort * > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1OutputPortVector_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< OutputPort * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< OutputPort * > *)new std::vector< OutputPort * >();
  *(std::vector< OutputPort * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1OutputPortVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< OutputPort * >::size_type arg1 ;
  std::vector< OutputPort * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< OutputPort * >::size_type)jarg1; 
  result = (std::vector< OutputPort * > *)new std::vector< OutputPort * >(arg1);
  *(std::vector< OutputPort * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  std::vector< OutputPort * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  result = ((std::vector< OutputPort * > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  std::vector< OutputPort * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  result = ((std::vector< OutputPort * > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  std::vector< OutputPort * >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  arg2 = (std::vector< OutputPort * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  result = (bool)((std::vector< OutputPort * > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  std::vector< OutputPort * >::value_type *arg2 = 0 ;
  std::vector< OutputPort * >::value_type temp2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  temp2 = *(std::vector< OutputPort * >::value_type *)&jarg2;
  arg2 = (std::vector< OutputPort * >::value_type *)&temp2; 
  (arg1)->push_back((std::vector< OutputPort * >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  int arg2 ;
  std::vector< OutputPort * >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< OutputPort * >::value_type *) &std_vector_Sl_OutputPort_Sm__Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< OutputPort * >::value_type *)&jresult = *result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPortVector_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  int arg2 ;
  std::vector< OutputPort * >::value_type *arg3 = 0 ;
  std::vector< OutputPort * >::value_type temp3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  arg2 = (int)jarg2; 
  temp3 = *(std::vector< OutputPort * >::value_type *)&jarg3;
  arg3 = (std::vector< OutputPort * >::value_type *)&temp3; 
  try {
    std_vector_Sl_OutputPort_Sm__Sg__set(arg1,arg2,(OutputPort *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1OutputPortVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< OutputPort * > *arg1 = (std::vector< OutputPort * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< OutputPort * > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1PropertyVector_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  std::vector< Property * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (std::vector< Property * > *)new std::vector< Property * >();
  *(std::vector< Property * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_new_1PropertyVector_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::vector< Property * >::size_type arg1 ;
  std::vector< Property * > *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (std::vector< Property * >::size_type)jarg1; 
  result = (std::vector< Property * > *)new std::vector< Property * >(arg1);
  *(std::vector< Property * > **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  std::vector< Property * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  result = ((std::vector< Property * > const *)arg1)->size();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1capacity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  std::vector< Property * >::size_type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  result = ((std::vector< Property * > const *)arg1)->capacity();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1reserve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  std::vector< Property * >::size_type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  arg2 = (std::vector< Property * >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT jboolean JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1isEmpty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  result = (bool)((std::vector< Property * > const *)arg1)->empty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  std::vector< Property * >::value_type *arg2 = 0 ;
  std::vector< Property * >::value_type temp2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  temp2 = *(std::vector< Property * >::value_type *)&jarg2;
  arg2 = (std::vector< Property * >::value_type *)&temp2; 
  (arg1)->push_back((std::vector< Property * >::value_type const &)*arg2);
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  int arg2 ;
  std::vector< Property * >::value_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Property * >::value_type *) &std_vector_Sl_Property_Sm__Sg__get(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return 0;
  }
  
  *(std::vector< Property * >::value_type *)&jresult = *result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_PropertyVector_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  int arg2 ;
  std::vector< Property * >::value_type *arg3 = 0 ;
  std::vector< Property * >::value_type temp3 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  arg2 = (int)jarg2; 
  temp3 = *(std::vector< Property * >::value_type *)&jarg3;
  arg3 = (std::vector< Property * >::value_type *)&temp3; 
  try {
    std_vector_Sl_Property_Sm__Sg__set(arg1,arg2,(Property *const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1PropertyVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  std::vector< Property * > *arg1 = (std::vector< Property * > *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::vector< Property * > **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_InputPort_1getName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  InputPort *arg1 = (InputPort *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InputPort **)&jarg1; 
  result = (arg1)->getName();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_OutputPort_1getName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OutputPort *arg1 = (OutputPort *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OutputPort **)&jarg1; 
  result = (arg1)->getName();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1Property(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Property *arg1 = (Property *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Property **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_Property_1getName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Property *arg1 = (Property *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Property **)&jarg1; 
  result = (arg1)->getName();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18UC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8UC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18UC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8UC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18UC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8UC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18UC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8UC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18SC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8SC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18SC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8SC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18SC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8SC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_18SC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_8SC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116UC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16UC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116UC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16UC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116UC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16UC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116UC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16UC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116SC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16SC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116SC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16SC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116SC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16SC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_116SC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_16SC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132SC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32SC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132SC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32SC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132SC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32SC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132SC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32SC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132FC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32FC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132FC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32FC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132FC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32FC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_132FC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_32FC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_164FC1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_64FC1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_164FC2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_64FC2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_164FC3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_64FC3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_IMAGE_1DATA_1TYPE_164FC4_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  ImageDataType result;
  
  (void)jenv;
  (void)jcls;
  result = (ImageDataType)IMAGE_DATA_TYPE_64FC4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_ExecutionModel_1createFilterChain(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  ExecutionModel *arg1 = (ExecutionModel *) 0 ;
  FilterChainPtr result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ExecutionModel **)&jarg1; 
  result = (arg1)->createFilterChain();
  *(FilterChainPtr **)&jresult = result ? new FilterChainPtr(result) : 0; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_ExecutionModel_1loadFilterChain(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jlong jresult = 0 ;
  ExecutionModel *arg1 = (ExecutionModel *) 0 ;
  std::string arg2 ;
  FilterChainPtr result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ExecutionModel **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->loadFilterChain(arg2);
  *(FilterChainPtr **)&jresult = result ? new FilterChainPtr(result) : 0; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_ExecutionModel_1saveFilterChain(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3) {
  ExecutionModel *arg1 = (ExecutionModel *) 0 ;
  FilterChainPtr arg2 ;
  std::string arg3 ;
  FilterChainPtr *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(ExecutionModel **)&jarg1; 
  argp2 = *(FilterChainPtr **)&jarg2; 
  if (argp2) arg2 = *argp2; 
  if(!jarg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return ;
  } 
  const char *arg3_pstr = (const char *)jenv->GetStringUTFChars(jarg3, 0); 
  if (!arg3_pstr) return ;
  (&arg3)->assign(arg3_pstr);
  jenv->ReleaseStringUTFChars(jarg3, arg3_pstr); 
  (arg1)->saveFilterChain(arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_ExecutionModel_1getLoadedFilterLibraries(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  ExecutionModel *arg1 = (ExecutionModel *) 0 ;
  std::vector< FilterLibrary * > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ExecutionModel **)&jarg1; 
  result = (arg1)->getLoadedFilterLibraries();
  *(std::vector< FilterLibrary * > **)&jresult = new std::vector< FilterLibrary * >((const std::vector< FilterLibrary * > &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_ExecutionModel_1getInstance(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ExecutionModel *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ExecutionModel *) &ExecutionModel::getInstance();
  *(ExecutionModel **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1FilterLibrary(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FilterLibrary **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jboolean JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1isValid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  result = (bool)(arg1)->isValid();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1getVendor(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  result = (arg1)->getVendor();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1getName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  result = (arg1)->getName();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1getVersion(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  result = (arg1)->getVersion();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1getLibraryName(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  result = (arg1)->getLibraryName();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1getFilterClassNames(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  std::vector< std::string > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  result = (arg1)->getFilterClassNames();
  *(std::vector< std::string > **)&jresult = new std::vector< std::string >((const std::vector< std::string > &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterLibrary_1buildFilter(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  FilterLibrary *arg1 = (FilterLibrary *) 0 ;
  std::string arg2 ;
  std::string arg3 ;
  Filter *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FilterLibrary **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if(!jarg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null std::string");
    return 0;
  } 
  const char *arg3_pstr = (const char *)jenv->GetStringUTFChars(jarg3, 0); 
  if (!arg3_pstr) return 0;
  (&arg3)->assign(arg3_pstr);
  jenv->ReleaseStringUTFChars(jarg3, arg3_pstr); 
  result = (Filter *)(arg1)->buildFilter(arg2,arg3);
  *(Filter **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_delete_1FilterChain(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  FilterChain *arg1 = (FilterChain *) 0 ;
  boost::shared_ptr< FilterChain > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  
  smartarg1 = *(boost::shared_ptr<  FilterChain > **)&jarg1;
  arg1 = (FilterChain *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterChain_1addFilter(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  FilterChain *arg1 = (FilterChain *) 0 ;
  Filter *arg2 = (Filter *) 0 ;
  boost::shared_ptr< FilterChain > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  
  smartarg1 = *(boost::shared_ptr<  FilterChain > **)&jarg1;
  arg1 = (FilterChain *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = *(Filter **)&jarg2; 
  (arg1)->addFilter(arg2);
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_FilterChain_1execute(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  FilterChain *arg1 = (FilterChain *) 0 ;
  boost::shared_ptr< FilterChain > *smartarg1 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  
  smartarg1 = *(boost::shared_ptr<  FilterChain > **)&jarg1;
  arg1 = (FilterChain *)(smartarg1 ? smartarg1->get() : 0); 
  (arg1)->execute();
}


SWIGEXPORT void JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_Filter_1execute(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Filter *arg1 = (Filter *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Filter **)&jarg1; 
  (arg1)->execute();
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_Filter_1getInputPorts(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Filter *arg1 = (Filter *) 0 ;
  std::vector< InputPort * > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Filter **)&jarg1; 
  result = (arg1)->getInputPorts();
  *(std::vector< InputPort * > **)&jresult = new std::vector< InputPort * >((const std::vector< InputPort * > &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_Filter_1getOutputPorts(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Filter *arg1 = (Filter *) 0 ;
  std::vector< OutputPort * > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Filter **)&jarg1; 
  result = (arg1)->getOutputPorts();
  *(std::vector< OutputPort * > **)&jresult = new std::vector< OutputPort * >((const std::vector< OutputPort * > &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_im_jeanfrancois_opencvp_nativeinterface_internal_opencvpJNI_Filter_1getProperties(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Filter *arg1 = (Filter *) 0 ;
  std::vector< Property * > result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Filter **)&jarg1; 
  result = (arg1)->getProperties();
  *(std::vector< Property * > **)&jresult = new std::vector< Property * >((const std::vector< Property * > &)result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

